import './globals.css'
import { Inter } from 'next/font/google'
import StyledComponentsRegistry from './registry';
import Menu from './menu/page';
import Footer from './footer/page';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <Menu></Menu>
          <main>
            {children}
          </main>
          <Footer>
          </Footer>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
