import './globals.css'
import { Inter } from 'next/font/google'
import StyledComponentsRegistry from './registry';
import MenuComponent from './components/menu';
import Footer from './components/footer';
import Menu from './components/menu';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const props = await getData();
  const footers = props.footers;
  const menus = props.menus;

  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <>
            <Menu menus={menus} />
            <main>
              {children}
            </main>
            <Footer footers={footers} />
          </>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
async function getData() {

  const footers = await fetch('https://hamoa-tech-strapi.onrender.com/api/footer?populate=*');
  const menus = await fetch('https://hamoa-tech-strapi.onrender.com/api/menu?populate=*');

  const res = {

    footers: await footers.json(),
    menus: await menus.json(),
  }

  if (!res) {
    throw new Error('Failed to fetch data');
  }

  return res;
}
